[build]
  # Si tu index.html está en la raíz, usa "."
  # Si está en una carpeta 'public', usa "public/"
  publish = "." 

[functions]
  directory = "functions/"
  node_bundler = "esbuild" # Recomendado para mejor rendimiento

# Cron Job: Se ejecuta a las 00:00 y 12:00 todos los días
[functions.scheduled-refresh]
  schedule = "0 */12 * * *"
